(continue)
(continue label)
(break)
(break label)
(fallthrough)
(fallthrough label)
(return)
(return expression)
raise
(raise expression)
(yield)
(yield expression)
(yield expression)
(yield break)
(yield break label)
(yield from)
(yield from expression)
