(annotation/list space)
(annotation/list decorator)
(define/class Empty (modifiers))
(annotation/list decorator)
(union Empty)
(define/class
  ClassA
  (modifiers)
  (annotation/list decorator)
  (class/field field (modifiers))
  (class/field field (modifiers public static) : A)
  (class/method method (modifiers))
  (class/method `/` (modifiers infix))
  (annotation/list inline)
  (class/method join (modifiers)))
(union UnionA)
