(for ((i)) in list (looping) else ())
(for ((i)) in (call/subscript1 ℤ (subscript1 (range (- 1) 1 null))) () else ())
(for ((i)) in (call/subscript0 ℤ (subscript0 (range (- 1) 1 2))) if (if (> i 0)) () else ())
(for ((k) (v)) in dict ((for ((i) (j)) in list (looping) else ())) else ())
(for ((k) (mut v)) in dict if (if (> k 0)) (looping) else ())
(for ((k) (mut v)) in dict if (if (> k 0)) (looping) else ((else (nothing))))
