(for ((i)) in list if true (looping) else ())
(for ((i)) in (call/subscript1 ℤ (subscript1 (range (- 1) 1 null))) if true () else ())
(for ((i)) in (call/subscript0 ℤ (subscript0 (range (- 1) 1 2))) if (> i 0) () else ())
(for ((k) (v)) in dict if true ((for ((i) (j)) in list if true (looping) else ())) else ())
(for ((k) (mut v)) in dict if (> k 0) (looping) else ())
(for ((k) (mut v)) in dict if (> k 0) (looping) else (nothing))
