(apply f)
(apply f 1)
(apply f (k 1))
(apply f null (a 1) (⁑ args) (⁂ kwargs))
(apply (apply (apply (apply f) 1) 1 2) 1 2 3)
(apply-dot a b)
(apply-dot a b)
(apply-dot (apply-dot a b) c)
(apply (apply (apply-dot (apply (apply-dot (apply a 1) b 1) 2) b 1) 2) 3)
