(call/apply f (apply))
(call/apply f (apply 1))
(call/apply f (apply (k 1)))
(call/apply f (apply null (a 1) (⁑ args) (⁂ kwargs)))
(call/apply (call/apply (call/apply (call/apply f (apply)) (apply 1)) (apply 1 2)) (apply 1 2 3))
(call/apply-dot a (b))
(call/apply-dot a (b))
(call/apply-dot (call/apply-dot a (b)) (c))
(call/apply (call/apply (call/apply-dot (call/apply (call/apply-dot (call/apply a (apply 1)) (b 1)) (apply 2)) (b 1)) (apply 2)) (apply 3))
