(new (generic) (apply))
(new (generic) (apply))
(new (generic) (apply))
(new (generic) (apply))
(new (generic) (apply))
(new (generic) (apply) term)
(new (generic) (apply 10) 0 1 2 3 4 5 6 7 8 9)
(new (generic (T Integer)) (apply (capacity 10)) 0 1 2 3 4 5 6 7 8 9)
(new (generic) (apply) item1 item2 (table tuple1) (table key value) (key value))
