(new A (generic) (apply))
(new B (generic) (apply))
(new C (generic) (apply))
(new D (generic) (apply))
(new E (generic) (apply))
(new List (generic) (apply) term)
(new Integer (generic A) (apply))
(new List (generic A) (apply))
(new List (generic) (apply 10) 0 1 2 3 4 5 6 7 8 9)
(new List (generic (T Integer)) (apply (capacity 10)) 0 1 2 3 4 5 6 7 8 9)
(new Object (generic) (apply) item1 item2 (table tuple1) (table key value) (key value))
(new
  BaseballTeam
  (generic T)
  (apply args)
  (name object one)
  (Size Math∷PI)
  (subscript1 RF Mookie Betts)
  (subscript1 CF Mike Trout)
  key
  (table key)
  (table key value)
  (table key value1 value2)
  (new
    IndexersExample
    (generic)
    (apply)
    (subscript1 1 1)
    (subscript1 2 4)
    (subscript1 3 9)
    (subscript1 C 4 Middle C)
    (subscript1 A 4 440 Hz)
    (subscript1 F 7 F above middle C)
    (subscript1 C A 0 C above A above C above middle C))
  (subscript1 4 Jose Altuve))
