(new (generic) (apply))
(new (generic) (apply))
(new (generic) (apply))
(new (generic) (apply))
(new (generic) (apply))
(new (generic) (apply) term)
(new (generic A) (apply))
(new (generic A) (apply))
(new (generic) (apply 10) 0 1 2 3 4 5 6 7 8 9)
(new (generic (T Integer)) (apply (capacity 10)) 0 1 2 3 4 5 6 7 8 9)
(new (generic) (apply) item1 item2 (table tuple1) (table key value) (key value))
(new
  (generic T)
  (apply args)
  (a b)
  ((subscript1 RF) Mookie Betts)
  ((subscript1 CF) Mike Trout)
  (table key value)
  (new (generic) (apply) (name object one) (Size Math∷PI) ((subscript1 1) 1) ((subscript1 2) 4) ((subscript1 3) 9) ((subscript1 C 4) Middle C))
  ((subscript1 4) Jose Altuve))
