(define/class A (modifiers))
(define/class B (modifiers value))
(define/class Positive (modifiers refine))
(define/class A (modifiers))
(define/class B (modifiers))
(define/class A (modifiers))
(define/class A (modifiers))
(define/class Empty1 (modifiers))
(define/class Empty2 (modifiers))
(define/class Empty3 (modifiers public static dynamic_transaction_safe volatile final))
(define/class Inherit1 (modifiers open impart))
(define/class Inherit2 (modifiers open impart))
(define/class 原神 (modifiers))
(define/class ClassA (modifiers))
(define/class TestClass (modifiers))
(define/class Class (modifiers))
