(define/class A (modifiers))
(define/class B (modifiers value))
(define/class Positive (modifiers refine))
(define/class A (modifiers) (class/field Base (modifiers inherit)) (class/field Base2 (modifiers inherit)))
(define/class B (modifiers) (class/field item (modifiers)))
