a∷b∷c
(- (+ a b) c)
(/ (* a b) c)
(^ a (^ b c))
(^ 5 (- (* 4 (+ 3 2)) 1))
(+ 1 (* 2 (^ 3 (- 4 5))))
(/% a 2)
(% (% 3))
(≖ 4a c)
(≠ (≠ a b) c)
(> (> a b) c)
(⩾ (⩾ (⩾ a (+ b c)) (+ c e)) d)
(< (< a b) c)
(⩽ (⩽ (⩽ a b) c) d)
(??? (??? (??? a b) c) d)
(??? (??? a b) c)
(??? (??? a b) c)
(??? (??? (??? a b) c) d)
(∈ a list)
(∈ a list)
(∉ a list)
(∈ a list)
(∉ a list)
(⊑ a String)
(⋢ b String)
(== (⍲ (∧ (≠ (⍱ (∨ (∨ (∧ a b) c) d) e) f) g) h) i)
