(micro function (arguments) (body))
(macro module∷function (arguments) (body))
(micro function (arguments ((a) Any null) ((k) T null) ((p) U 1)) (body (apply print Hello, world!)))
(micro function (arguments ((g) G null)) (body (apply print Hello, world!)))
(micro function (arguments ((g) G 0)) (body (macro function (arguments ((g) G null)) (body (apply print Hello, world!)))))
